### ISSUE TITLE
TBS5580 is missing fixes c96944e: Use heap buffer for USB I/O

### ISSUE THREAD

**Issue by mmajoor** [tbsdtv/linux_media#106]
For the TBS5580 the fixes that are applied in commit https://github.com/tbsdtv/linux_media/commit/c96944e5b356ff950c6d3a790e27b240e334623a are mssing (leading to failure when loading the firmware etc)..
Possible patch:
[linux_media-latest.zip](https://github.com/tbsdtv/linux_media/files/1713323/linux_media-latest.zip)

**Comment by crazycat69** [comment]
c7e7de8b04df9b4344426fefe637f23e4081a82c
