### ISSUE TITLE
latest version compile fails

### ISSUE THREAD

**Issue by hamishegg** [tbsdtv/linux_media#11]
/root/builds/media_build/v4l/em28xx-dvb.c:45:31: fatal error: drx39xyj/drx39xxj.h: No such file or directory
 #include "drx39xyj/drx39xxj.h"

**Comment by ovidiu31** [comment]
FAQ:

1./bin/sh: 1: lsdiff: not found
sudo apt-get install patchutils

2.you may need to install the Proc::ProcessTable module
sudo apt-get install libproc-processtable-perl

**_3.fatal error: drx39xyj/drx39xxj.h: No such file or directory
mkdir -p v4l/drx39xyj
cp v4l/drx39xxj.h v4l/drx39xyj/_**

4.Can not find the 6909 firmware
wget http://www.tbsdtv.com/download/document/linux/dvb-fe-mxl5xx.fw
cp dvb-fe-mxl5xx.fw /lib/firmware/

5.If you find module load errors like "module has wrong symbol version" means that there still are old modules from your previous media tree installation (usually duplicated modules in two different places).
sudo rm -rf /lib/modules/uname -r/kernel/drivers/media/*

6.Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9
·sudo rm /usr/bin/gcc sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc`

Please refer to LinuxTV wiki page for more info about the build process: LinuxTV Wiki

In addition to following the above instructions, TBS6980/1/4 owners will need to put a copy of the CX24117 firmware in /lib/firmware/
