### ISSUE TITLE
drivers not working for TBS6205

### ISSUE THREAD

**Issue by snake2005** [tbsdtv/linux_media#12]
please see dmesg

http://pastebin.com/RPJeWfU3

**Comment by ovidiu31** [comment]
you need to update your bios to a newer version.
i2c errors are from an outdated bios or an pcie motherboard issue

**Comment by CHBMB** [comment]
Can confirm these are working for my TBS6205....

**Comment by ovidiu31** [comment]
@snake2005 please close the issue if you confirmed as was fixed.

**Comment by snake2005** [comment]
fixed. sorry for my delayed answer.
