### ISSUE TITLE
driver install error

### ISSUE THREAD

**Issue by snake2005** [tbsdtv/linux_media#13]
make[1]: *** No rule to make target '../linux/drivers/media/platform/s5p-tv/Kconfig', needed by 'Kconfig'.  Stop.
make[1]: Leaving directory '/home/administrator/tbsdriver/media_build/v4l'
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ovidiu31** [comment]
its not driver install error ... it is compiling error ... seems you missing some dependencies or libraries

**Comment by steven1758** [comment]
please contact our support@tbsdtv.com to check more detail information

**Comment by snake2005** [comment]
fixed. thx

**Comment by kalle006** [comment]
Hey,
i have the same problem, how did you solve it??
greez Kalle
