### ISSUE TITLE
Please help how to install on centos 6

### ISSUE THREAD

**Issue by nightshadow36** [tbsdtv/linux_media#14]
Hi.
I have a server that i changed from ubuntu to centos as ubuntu always updates the kernal
I am unable to get it installed on centos using the guide.
Is there anything extra i need to install or add to get it installed?
Thank you

**Comment by steven1758** [comment]
Hi 

Please have a try lke this :
1.update to new kernel
#rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
#rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
#yum --enablerepo=elrepo-kernel install kernel-lt-devel kernel-lt -y
#grub2-set-default 0 

2.
#reboot

3.
#yum -y install perl-devel perl-ExtUtils-CBuilder perl-ExtUtils-MakeMaker
#yum -y install patchutils
#yum -y install patch

4.
#wget https://sourceforge.net/projects/moiproamd/files/Files/Digest-SHA-5.93.tar.gz/download
#tar xvf   Digest-SHA-5.95.tar.gz
#perl Makefile.PL
#make && make install

5.
#wget https://sourceforge.net/projects/moiproamd/files/Files/perl-proc-processtable-master.zip/download
#unzip perl-proc-processtable-master.zip
#perl Makefile.PL
#make && make install

6.Install the open sourece driver:
check this 
https://github.com/tbsdtv/linux_media/wiki

thanks

**Comment by ovidiu31** [comment]
@steven1758 

its working Steve , you can close this issue.
