### ISSUE TITLE
Driver Build not OK under kernel 4.19

### ISSUE THREAD

**Issue by jpg73** [tbsdtv/linux_media#147]
Dear, 
compiling was OK with 4.15, 4.16, 4.18  , but failed under 4.19
please see http://paste.ubuntu.com/p/QqwFbV98Vy/
Any advice ?
THX
JP

**Comment by crazycat69** [comment]
no merget yes with latest media_tree, wait some days.

**Comment by crazycat69** [comment]
updated, please check again with 4.19

**Comment by alanswanson** [comment]
Build still failing with 4.19 at si2183.c as i2c_[un]lock_adapter were removed upstream in this  [commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=3f3a89e1d7c31558c070692241e3d6146d2cf1bf). Changing to i2c_[un]lock_bus with I2C_LOCK_ROOT_ADAPTER per commit message, compile succeeds but I've not runtime tested yet.

**Comment by crazycat69** [comment]
303ceb42a0d3a5a0da0d629e47b12b9ca4634853

**Comment by jpg73** [comment]
works ! 👍 THX a lot CC
JP
