### ISSUE TITLE
Doesn't work on PROXMOX os (debian)

### ISSUE THREAD

**Issue by kralsam** [tbsdtv/linux_media#154]
After I upgrade my server os, TBS driver didn't work .  I compiled and make install this driver on proxmox os. But doesn't work it. Kernel ver: (uname -r : 4.15.18-11-pve)

**Comment by tbsiptv** [comment]
Hi compile and install is it have any error ?if not please have a try update the kernel to 4.16 or 4.18 then try again 

thanks

**Comment by crazycat69** [comment]
remove kernel media drivers before install
`sudo rm -r -f /lib/modules/$(uname -r)/kernel/drivers/media`

or use **[media_build/install.sh](https://github.com/tbsdtv/media_build/blob/master/install.sh)** script for compile, remove old media modules and install.

**Comment by kralsam** [comment]
Ok. Thanks a lot. 
Solved problem.
