### ISSUE TITLE
"ts discontinuity" issue with TBS6909

### ISSUE THREAD

**Issue by tonygables** [tbsdtv/linux_media#16]
Hi,

I installed the latest open source drivers but TBS6909 works very unstable. Lots of "TS discontinuity" errors. If I lock to the same frequency using TBS6905 or TBS6910 no errors at all. 

Then I switch back to closed source drivers v160219 and TBS6909 works fine. 

OS: Ubuntu 16.04 (64 Bit)
Kernel: 4.4.0-42-generic 
DVBlast 3.0

**Comment by ovidiu31** [comment]
@tonygables 

you using mode 0 or mode 1 for 6909?

**Comment by tonygables** [comment]
Mode 0

**Comment by tonygables** [comment]
This issue is fixed after the update two days ago. Thanks.
