### ISSUE TITLE
Can't compile latest on kernel 3.13

### ISSUE THREAD

**Issue by nrmmota** [tbsdtv/linux_media#160]
Latest linux_media
commit 35e13036285523588b90e0153f9af820fb8b74a9
Author: CrazyCat <crazycat69@narod.ru>
Date:   Wed May 8 19:48:07 2019 +0300

    stid135: Improved signal status reading.

Latest media_build
commit fa150d8eaf8ec0afea5ef2fdd6e42c8bbe436c59
Author: tbsiptv <tbsiptv@gmail.com>
Date:   Sun Apr 28 10:08:13 2019 +0800

    Update v4.5_get_user_pages.patch
    
    Temporary backport patch fix for 4.4.168+ compatibility.

ubuntu@ubuntu-server:~/tbs_github_drivers/media_build$ uname -r
3.13.0-117-generic

**Comment by crazycat69** [comment]
Revert latest media_build commit

**Comment by nrmmota** [comment]
Yap, that worked.
Thank you.
