### ISSUE TITLE
stid135_drv.c  signed frequency_hz variable may overflow

### ISSUE THREAD

**Issue by JianSun1** [tbsdtv/linux_media#181]
[In this function](https://github.com/tbsdtv/linux_media/blob/59b57115beb2195d7a0ed11323ca0ee9bf5d5679/drivers/media/dvb-frontends/stid135/stid135_drv.c#L799) and [ in this line ](https://github.com/tbsdtv/linux_media/blob/59b57115beb2195d7a0ed11323ca0ee9bf5d5679/drivers/media/dvb-frontends/stid135/stid135_drv.c#L854)if user wants to tune a specific range of freqency which is shown below may fail because of signed variable.

```
0x7FFFFFF<freq<2150MHz 
``` 

(Note: 0x7FFFFFFF is 2147483647 in decimals.)
For instance, lets select a  frequency value of 2148000000Hz, then it will be negative number and the calculations in this may fail;
``` 
si_register = ((frequency_hz/PLL_FVCO_FREQUENCY)*cfr_factor)/100
```
I am not sure if the next lines can handle this. I noticed that when i was looking into the code.

**Comment by crazycat69** [comment]
frequency_hz=-550MHz..+650MHz
