### ISSUE TITLE
Incorrect testing for mcu_busy in  tbs6301_read_mac

### ISSUE THREAD

**Issue by tvhdeeptho** [tbsdtv/linux_media#187]
This code produces a compiler warning and is obviously wrong.
```
if((tmpbuf[0]&0x4) == 1) 
```
Two such lines occur and should be replaced by
```
if((tmpbuf[0]&0x4) == 0x4) 
`

**Comment by tvhdeeptho** [comment]
Path for this issue
[patch0.txt](https://github.com/tbsdtv/linux_media/files/4114599/patch0.txt)

**Comment by crazycat69** [comment]
or just if(tmpbuf[0]&0x4)
