### ISSUE TITLE
Can not Load mn88436 driver.

### ISSUE THREAD

**Issue by zmdk0913** [tbsdtv/linux_media#195]
I installed tbsdtv driver follows menual, So I complete build and install on my linux ubuntu 19.04 kernel 5.4.0-rc1.
And I typed this command 'modprobe mn88436, modprobe mxl603, modprobe dvb-usb-cxusb'
And I reboot server and command typed. dmesg
USB Tuner A681 is can saw, but about DVB enabled don't see. Why I have problem? Please help me.

**Comment by crazycat69** [comment]
Yoy must add support for your usb stick to cxusb driver :)

**Comment by zmdk0913** [comment]
how can I add cxusb deiver?I installed dvb-usb-cxusb, Shoud I need to install another?
I use Mygica a681(mohu)

**Comment by crazycat69** [comment]
add device usb id and tuner/frontend attach

**Comment by zmdk0913** [comment]
I don't know anything. Can you help me with command?

**Comment by crazycat69** [comment]
better try support from Chris Lee - [v4l-updatelee](https://gitlab.com/updatelee/v4l-updatelee)
some descriptions from US - https://rickcaylor.websitetoolbox.com/post/v4lupdatelee-6433163?pid=1309850794&highlight=a681

this based on Geniatech V4L DVB sources for mxl603/mn88436
https://gitlab.com/updatelee/v4l-updatelee/-/blob/master/drivers/media/tuners/mxl603.c
https://gitlab.com/updatelee/v4l-updatelee/-/blob/master/drivers/media/dvb-frontends/mn88436.c
https://gitlab.com/updatelee/v4l-updatelee/-/blob/master/drivers/media/usb/dvb-usb/cxusb.c#L1406
