### ISSUE TITLE
Enable blind scan support for TBS5520 SE in drivers

### ISSUE THREAD

**Issue by Kitoko86** [tbsdtv/linux_media#198]
Hi,

Is it possible to get blind scan support for tbs 5520 SE in Linux drivers? If not, could you give a patch that would enable this feature? Thanks in advance.

**Comment by tbsiptv** [comment]
sorry that for 5520se the chipset do not support blindscan

**Comment by tbsiptv** [comment]
if you want blindscan you can try with TBS6903 6908
