### ISSUE TITLE
Patch for kernel 4.9

### ISSUE THREAD

**Issue by Xxyzzy** [tbsdtv/linux_media#20]
At your own risk. No support.
[patch-kernel-4.9.txt](https://github.com/tbsdtv/linux_media/files/646646/patch-kernel-4.9.txt)

**Comment by CvH** [comment]
I guess `CONFIG_SAA716X_SUPPORT` is still not working with that ?

**Comment by crazycat69** [comment]
tbsdtv/media_tree and tbsdtv/media_build updated with latest for 4.9 compatibility.

**Comment by CvH** [comment]
@crazycat69 does the mismatch in `drivers/media/dvb-frontends/stv090x.c` get fixed ? 
besides that, the patch against plain 4.9 works after i added http://pastebin.com/JN8smBEy to the master branch 👍

**Comment by crazycat69** [comment]
All conflicts resolved
5c21ed51b3b110dcad6671a522a9bef1b9d2c904

**Comment by CvH** [comment]
sorry expressed too imprecise, if I create a patch `git diff master latest > ../tbs-49.patch` this patch can't be merged wit kernel 4.9 because of some mismatch in `stv090x.c` and `dw2102.c`. 
The master branch has not the 4.9 files for this two files (it includes addition commits).

**Comment by CvH** [comment]
@crazycat69 SAA716x is still (at least 4.8 won't work either) not working -> [error](http://pastebin.com/bVRetWrL) ([full log](http://pastebin.com/Y6etshst))
if I build without `SAA716x` it works like a charm 👍
