### ISSUE TITLE
TBS 5520SE issues with Tvheadend

### ISSUE THREAD

**Issue by smp79** [tbsdtv/linux_media#229]
I opened an [issue report](https://tvheadend.org/issues/5990) on Tvheadend site. Can anyone help to fix this?

Tvheadend developer say he can't investigate this issue because he doesn't have the 5520SE.

**Comment by crazycat69** [comment]
you must set frontends as linked in TVH (so if one used, second not usedby TVH)

**Comment by smp79** [comment]
I tried that, it doesn't fix the issue.
I did more testing and it can fail even with 1 tuner enabled. 

В VDR всё идеально работает. А в этом дурацком TVH сначала вроде бы работает, но после перезагрузки "no free adapters available" в Коди. Если в настройках TVH выключить и включить 1 тюнер, то может опять заработать.

**Comment by smp79** [comment]
У меня подозрение, что tvheadend-у не нравится, что у 5520SE 2 тюнера подцеплены к 1 демоду. Что подкрутить в драйвере, чтобы был только один FE на котором только DVB-S/S2?

**Comment by crazycat69** [comment]
Вообще-то там два фронтєнда на адаптер, что нужно так как физически два тюнера подключены к демодулятору. Очередность регистрации в tbs5520se_frontend_attach()
https://github.com/tbsdtv/linux_media/blob/latest/drivers/media/usb/dvb-usb/tbs5520se.c#L254

**Comment by smp79** [comment]
> Вообще-то там два фронтенда на адаптер, что нужно так как физически два тюнера подключены к демодулятору.

Это понятно, просто хочу добраться до корня проблемы с tvh.  Хочу собрать тестовый драйвер, чтобы tvh видел только DVB-S тюнер. Если это решит проблему, по крайней мере будет видно, в какую сторону копать.
