### ISSUE TITLE
TBS 6982, Kernel 4.9

### ISSUE THREAD

**Issue by maxodoble** [tbsdtv/linux_media#23]
Hi,

Building and Installation went fine,
and driver seems to work ok.

But the logs get spammed with messages like this (about every second five lines):

 dvb_demux: dvb_dmx_swfilter_section_packet: dvb_demux.c discontinuity detected 184 bytes lost

Cheers,
 Max

**Comment by wdirksen** [comment]
I get the same in dmesg.
I'm using 6984 + 6908 under Arch Linux kernel 4.8.13-1-ARCH

It runs fine here too. Doesn't seem good somehow

**Comment by crazycat69** [comment]
ae41834f7c07b39e1cc51261c8cef8294c1509a1
