### ISSUE TITLE
TBS 6504 unusable stream, "retune" issue

### ISSUE THREAD

**Issue by jadsonlourenco** [tbsdtv/linux_media#248]
The error:
After start few streams, I'm using 4 tuners, TVH show this error on all tuners, every 15 seconds:
```
2021-05-10 15:42:52.622 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #1 : DVB-S #1 - poll TIMEOUT
2021-05-10 15:42:53.907 TS: SAT-KU/12620H/Channel: MPEG2AUDIO @ #3232 Continuity counter error (total 19)
2021-05-10 15:42:54.063 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #1 : DVB-S #1 - retune
```

I've tested everything:
* other driver versions, from 2020; 
* old commits from this repo; 
* test one stream with one tuner enabled; 
* others Linux kernels (4.19, 5.1, 5.2, 5.4, 5.8, 5.10, 5.12); 
* Ubuntu 20.04 server, new install; Ubuntu desktop; 
* More power to the TBS device (from the adapter of this device, connected on sata port - 500W gold);
* Search on TBS forum;
* Search on TVH community;

Nothing fixed this issue.
Now I'm using Ubuntu desktop 20.04.2, kernel 5.8.0-43-generic, with 3 Nvidia 1660 super to transcoder. But like I said, even only single stream will get this issue, playing on LVC without transcode.

So, I think is a driver issue, because was working fine few weeks ago, before I upgrade the Ubuntu.
I'm on this for three days before open this issue. Someone can help? Thank you.

**Comment by crazycat69** [comment]
what satellite, transponder ? Signal Level, SNR ?

**Comment by jadsonlourenco** [comment]
70W, 12220H29900, Signal -37db (after splitter but even without get the same issue), SNR -11db.

Log:
```
2021-05-11 11:54:28.660 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #0 : DVB-S #1 - retune
2021-05-11 11:54:28.879 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #3 : DVB-S #1 - retune
2021-05-11 11:54:28.965 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #2 : DVB-S #1 - retune
2021-05-11 11:54:29.051 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #1 : DVB-S #1 - retune
2021-05-11 11:54:35.110 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #2 : DVB-S #1 - poll TIMEOUT
2021-05-11 11:54:35.111 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #0 : DVB-S #1 - poll TIMEOUT
2021-05-11 11:54:35.112 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #1 : DVB-S #1 - poll TIMEOUT
2021-05-11 11:54:35.113 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #3 : DVB-S #1 - poll TIMEOUT
2021-05-11 11:54:35.711 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #0 : DVB-S #1 - retune nodata
2021-05-11 11:54:35.930 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #3 : DVB-S #1 - retune nodata
2021-05-11 11:54:36.018 linuxdvb: TurboSight TBS 6504 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T  #2 : DVB-S #1 - retune nodata
```

I have another server with the same sat, but not TBS device, working fine, from the same antenna, second LNB output. I've replaced everything to test, only this TBS device get this issue, and is a driver issue.

**Comment by jadsonlourenco** [comment]
I did, nothing changed. 

I will remove the nvidia devices and test again, I'm using TVH over Docker, and the GPUs using PCIE risers (mining).

**Comment by crazycat69** [comment]
PCIe card in virtual machine ?

**Comment by jadsonlourenco** [comment]
What it's mean?
```
[   54.849973] si2183 1-0064: found a 'Silicon Labs Si2183-B60'
[   54.850597] si2183 1-0064: downloading firmware from file 'dvb-demod-si2183-b60-01.fw'
[   56.057802] si2183 1-0064: firmware version: 6.0.13
[   56.084638] si2157 10-0061: found a 'Silicon Labs Si2157-A30'
[   56.111609] si2157 10-0061: firmware version: 3.0.5
[   56.121850] TBSECP3 driver 0000:02:00.0: DVB: adapter 3 frontend 0 frequency 0 out of range (174000000..862000000)
[   56.368875] TBSECP3 driver 0000:02:00.0: DVB: adapter 3 frontend 1 frequency 0 out of range (950000..2150000)
[   56.375415] si2183 1-0067: found a 'Silicon Labs Si2183-B60'
[   56.375433] si2183 1-0067: downloading firmware from file 'dvb-demod-si2183-b60-01.fw'
[   57.595730] si2183 1-0067: firmware version: 6.0.13
[   57.622250] si2157 10-0060: found a 'Silicon Labs Si2157-A30'
[   57.649544] si2157 10-0060: firmware version: 3.0.5
[   57.660598] TBSECP3 driver 0000:02:00.0: DVB: adapter 2 frontend 0 frequency 0 out of range (174000000..862000000)
[   57.909047] TBSECP3 driver 0000:02:00.0: DVB: adapter 2 frontend 1 frequency 0 out of range (950000..2150000)
[   57.915883] si2183 2-0064: found a 'Silicon Labs Si2183-B60'
[   57.915901] si2183 2-0064: downloading firmware from file 'dvb-demod-si2183-b60-01.fw'
[   59.126816] si2183 2-0064: firmware version: 6.0.13
[   59.153406] si2157 9-0061: found a 'Silicon Labs Si2157-A30'
[   59.181384] si2157 9-0061: firmware version: 3.0.5
[   59.192447] TBSECP3 driver 0000:02:00.0: DVB: adapter 1 frontend 0 frequency 0 out of range (174000000..862000000)
[   59.437229] TBSECP3 driver 0000:02:00.0: DVB: adapter 1 frontend 1 frequency 0 out of range (950000..2150000)
[   59.443637] si2183 2-0067: found a 'Silicon Labs Si2183-B60'
[   59.443655] si2183 2-0067: downloading firmware from file 'dvb-demod-si2183-b60-01.fw'
[   60.676216] si2183 2-0067: firmware version: 6.0.13
[   60.704073] si2157 9-0060: found a 'Silicon Labs Si2157-A30'
[   60.730109] si2157 9-0060: firmware version: 3.0.5
[   60.740356] TBSECP3 driver 0000:02:00.0: DVB: adapter 0 frontend 0 frequency 0 out of range (174000000..862000000)
[   60.981480] TBSECP3 driver 0000:02:00.0: DVB: adapter 0 frontend 1 frequency 0 out of range (950000..2150000)
```

**Comment by jadsonlourenco** [comment]
Well I found the cause of this issue, the signal is lost many times after start a stream.

So, I have a splitter 1x4 (LNB > each tuner), I put a satlink on one of this out to see if the sinal is lost and it is! 

Then I've put a "basic" splitter, 1x2, one output to the main splitter (1x4) and the other output to satlink; when satlink is ON it send the energy to power the LNB, and the sinal works fines, when it's off the sinal on the main splitter start to drop.

Then I put only the basic splitter to TBS (one tuner only) and satlink, works well.
When I put two TBS tuners to this basic splitter output not work well, drop signal. 

Now I'm using one tuner without splitter and works fine.

So, can be a config about energy from TBS tuner to the LNB or a signal strength, the signal with splitter is -37db, are good?

**Comment by jadsonlourenco** [comment]
Ok, now I discovered that if I connect the tunner 0 cable with any other tuner get this issue. If not use this tuner 0, but the others three simultaneous works fine. I'v replace the tuner 0 cable to see if works.

**Comment by jadsonlourenco** [comment]
Well, the issue is not with DRIVER, are the splitters, even new one, sorry for the inconvenience, and thank you for the help.
