### ISSUE TITLE
Silicon Labs Tuner and Demodulator

### ISSUE THREAD

**Issue by 4l3x2k** [tbsdtv/linux_media#252]
This issue is only for record. For me or anyone else who has time.

Silicon Labs provide and opened their source for some tuner and demodulator ics since 2020.

Check this out for Si demodulators https://github.com/SiliconLabs/video_si21xx_superset

Please add a label for Documentation or Feature.

**Comment by crazycat69** [comment]
Thanks :) Look like Silabs make proper choice - from "deep dark" closed-source for each chip to unified "superset sources" and open-source :)
