### ISSUE TITLE
TBS6209, Debian 10, Kernel 4.19.0-18 DVB-C not working correctly

### ISSUE THREAD

**Issue by mthqwork** [tbsdtv/linux_media#270]
After a few channel switches, the tuner cannot tune that frequency anymore. Only closing the software and reopening solves it - or may not.

[Sun Jan 16 12:36:46 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:36:46 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:36:52 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:36:52 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:36:59 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:36:59 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:37:06 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:37:06 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:37:14 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:37:14 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:37:23 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:37:23 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:37:33 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:37:33 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:37:42 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:37:42 2022] si2183 11-0067: set_params failed=-11
[Sun Jan 16 12:37:51 2022] si2183 11-0067: err setting tuner params
[Sun Jan 16 12:37:51 2022] si2183 11-0067: set_params failed=-11

I am on latest FW and driver. Any suggestions?
This happens with minisatip and tvheadend as well.

Have tried with 3 cards, should not be a HW issue. 
Have upgraded to Debian 11 & 5.10.0-10 and it's the same.
Made a fresh install of Debian 9, with 4.9.0-11 kernel and open source driver version 2017-07026 and looks like its working fine. So far no error messages like above. This will be problematic as Debian 9 supports end this summer.

**Comment by crazycat69** [comment]
fixed 7c4fb702fd57679ce082cbb089ca307e3f9b0682
