### ISSUE TITLE
Build fails in Fedora 36 kernel 5.18.5-200.fc36.x86_64

### ISSUE THREAD

**Issue by fe31nz** [tbsdtv/linux_media#286]
I tried compiling in a VirtualBox Fedora 36 with the current kernel (5.18.5-200.fc36.x86_64) and it fails on incompatible pointer types:

/root/projects/tbs6909-drivers/media_build/v4l/msi001.c:504:27: error: initialization of 'void (*)(struct spi_device *)' from incompatible pointer type 'int (*)(struct spi_device *)' [-Werror=incompatible-pointer-types]
  504 |         .remove         = msi001_remove,
      |                           ^~~~~~~~~~~~~

It looks like this warning is being upgraded to an error as a result of an option being passed to gcc, or maybe it is now the default with gcc 12.1.1 which is current on Fedora 36.  I have attached my full build script file and the log of its output:

./download_and_build.sh 2>&1 | tee build.log

**Comment by fe31nz** [comment]
Attaching the files did not work, so here they are:

download_and_build.sh:
#!/bin/bash

set -x
cd /root/projects/tbs6909-drivers || exit 1
rm -r media
rm -r media_build
git clone https://github.com/tbsdtv/media_build.git || exit 2
git clone --depth=1 https://github.com/tbsdtv/linux_media.git -b latest ./media || exit 3

cd media_build
make dir DIR=../media || exit 11
make allyesconfig || exit 12
make -j$(($(getconf _NPROCESSORS_ONLN)+1)) || exit 13
#make || exit 13

make install
#restart


build.log:
+ cd /root/projects/tbs6909-drivers
+ rm -r media
rm: cannot remove 'media': No such file or directory
+ rm -r media_build
+ git clone https://github.com/tbsdtv/media_build.git
Cloning into 'media_build'...
+ git clone --depth=1 https://github.com/tbsdtv/linux_media.git -b latest ./media
Cloning into './media'...
Updating files: 100% (74560/74560), done.
+ cd media_build
+ make dir DIR=../media
make -C linux/ dir DIR="../../media"
make[1]: Entering directory '/root/projects/tbs6909-drivers/media_build/linux'
rm -rf drivers include sound mm .patches_applied .linked_dir .git_log.md5 git_log kernel_version.h
Searching in ../../media/Makefile for kernel version.
./use_dir.pl ../../media
sync file: include/uapi/linux/cec.h
sync file: include/linux/atmel-isc-media.h
sync file: include/misc/altera.h
sync file: include/uapi/linux/v4l2-mediabus.h
sync file: include/linux/mmc/sdio_ids.h
sync file: include/uapi/linux/videodev2.h
sync file: include/uapi/linux/ccs.h
sync file: include/trace/events/pwc.h
sync file: include/uapi/linux/cec-funcs.h
sync file: include/linux/ti_wilink_st.h
sync file: include/uapi/linux/meye.h
sync file: include/uapi/linux/ivtvfb.h
sync file: include/linux/of_graph.h
sync file: include/uapi/linux/xilinx-v4l2-controls.h
sync file: sound/pci/bt87x.c
sync file: include/uapi/linux/ivtv.h
sync file: include/uapi/linux/lirc.h
sync file: include/trace/events/vb2.h
sync file: include/uapi/linux/media.h
sync file: include/sound/aci.h
sync file: include/uapi/linux/max2175.h
sync file: include/uapi/linux/v4l2-controls.h
sync file: include/uapi/linux/usb/video.h
sync file: include/trace/events/v4l2.h
sync file: include/linux/via-core.h
sync file: include/linux/hdmi.h
sync file: include/uapi/linux/uvcvideo.h
sync file: include/uapi/linux/v4l2-subdev.h
sync file: include/linux/fixp-arith.h
sync file: include/linux/dma/xilinx_dma.h
sync file: include/uapi/linux/v4l2-dv-timings.h
sync file: include/linux/pci_ids.h
sync file: include/linux/overflow.h
sync file: include/uapi/linux/v4l2-common.h
sync file: include/linux/kconfig.h
sync file: include/uapi/linux/media-bus-format.h
sync file: include/uapi/linux/smiapp.h
sync dir: include/media/
sync dir: include/uapi/linux/dvb/
sync dir: drivers/staging/media/
sync dir: drivers/media/
sync dir: include/linux/platform_data/media/
sync dir: include/dt-bindings/media/
sync dir: drivers/misc/altera-stapl/
make[1]: Leaving directory '/root/projects/tbs6909-drivers/media_build/linux'
+ make allyesconfig
make -C /root/projects/tbs6909-drivers/media_build/v4l allyesconfig
make[1]: Entering directory '/root/projects/tbs6909-drivers/media_build/v4l'
No version yet, using 5.18.5-200.fc36.x86_64
make[2]: Entering directory '/root/projects/tbs6909-drivers/media_build/linux'
Syncing with dir ../../media
Applying patches for kernel 5.18.5-200.fc36.x86_64
patch -s -f -N -p1 -i ../backports/api_version.patch
patch -s -f -N -p1 -i ../backports/pr_fmt.patch
patch -s -f -N -p1 -i ../backports/debug.patch
patch -s -f -N -p1 -i ../backports/drx39xxj.patch
patch -s -f -N -p1 -i ../backports/ccs.patch
patch -s -f -N -p1 -i ../backports/rc-cec.patch
Patched drivers/media/dvb-core/dvbdev.c
Patched drivers/media/v4l2-core/v4l2-dev.c
Patched drivers/media/rc/rc-main.c
Syncing with dir ../../media
make[2]: Leaving directory '/root/projects/tbs6909-drivers/media_build/linux'
./scripts/make_kconfig.pl /lib/modules/5.18.5-200.fc36.x86_64/build /lib/modules/5.18.5-200.fc36.x86_64/source 1
Preparing to compile for kernel version 5.18.5

***WARNING:*** You do not have the full kernel sources installed.
This does not prevent you from building the v4l-dvb tree if you have the
kernel headers, but the full kernel source may be required in order to use
make menuconfig / xconfig / qconfig.

If you are experiencing problems building the v4l-dvb tree, please try
building against a vanilla kernel before reporting a bug.

Vanilla kernels are available at http://kernel.org.
On most distros, this will compile a newly downloaded kernel:

cp /boot/config-`uname -r` <your kernel dir>/.config
cd <your kernel dir>
make all modules_install install

Please see your distro's web site for instructions to build a new kernel.

WARNING: This is the V4L/DVB backport tree, with experimental drivers
	 backported to run on legacy kernels from the development tree at:
		http://git.linuxtv.org/media-tree.git.
	 It is generally safe to use it for testing a new driver or
	 feature, but its usage on production environments is risky.
	 Don't use it in production. You've been warned.
CEC_CROS_EC: Requires at least kernel 9.255.255
V4L2_H264: Requires at least kernel 9.255.255
VIDEO_IPU3_CIO2: Requires at least kernel 9.255.255
VIDEO_OMAP3: Requires at least kernel 9.255.255
VIDEO_ROCKCHIP_ISP1: Requires at least kernel 9.255.255
VIDEO_MEM2MEM_DEINTERLACE: Requires at least kernel 9.255.255
VIDEO_HI556: Requires at least kernel 9.255.255
VIDEO_IMX208: Requires at least kernel 9.255.255
VIDEO_IMX258: Requires at least kernel 9.255.255
VIDEO_IMX274: Requires at least kernel 9.255.255
VIDEO_IMX319: Requires at least kernel 9.255.255
VIDEO_OV02A10: Requires at least kernel 9.255.255
VIDEO_OV2740: Requires at least kernel 9.255.255
VIDEO_OV5670: Requires at least kernel 9.255.255
VIDEO_OV5675: Requires at least kernel 9.255.255
VIDEO_OV772X: Requires at least kernel 9.255.255
VIDEO_OV8856: Requires at least kernel 9.255.255
VIDEO_OV9650: Requires at least kernel 9.255.255
SND_BT87X: Requires at least kernel 9.255.255
INTEL_ATOMISP: Requires at least kernel 9.255.255
VIDEO_HANTRO: Requires at least kernel 9.255.255
VIDEO_ROCKCHIP_VDEC: Requires at least kernel 9.255.255
VIDEO_IPU3_IMGU: Requires at least kernel 9.255.255
Created default (all yes) .config file
./scripts/fix_kconfig.pl
make[1]: Leaving directory '/root/projects/tbs6909-drivers/media_build/v4l'
++ getconf _NPROCESSORS_ONLN
+ make -j9
make -C /root/projects/tbs6909-drivers/media_build/v4l 
make[1]: Entering directory '/root/projects/tbs6909-drivers/media_build/v4l'
scripts/make_makefile.pl
./scripts/make_myconfig.pl
[ ! -f "./config-mycompat.h" ] && echo "/* empty config-mycompat.h */" > "./config-mycompat.h" || true
make -C firmware prep
creating symbolic links...
perl scripts/make_config_compat.pl /lib/modules/5.18.5-200.fc36.x86_64/source ./.myconfig ./config-compat.h
make[2]: Entering directory '/root/projects/tbs6909-drivers/media_build/v4l/firmware'
make[2]: Nothing to be done for 'prep'.
make[2]: Leaving directory '/root/projects/tbs6909-drivers/media_build/v4l/firmware'
make -C firmware
make[2]: Entering directory '/root/projects/tbs6909-drivers/media_build/v4l/firmware'
make[2]: Nothing to be done for 'default'.
make[2]: Leaving directory '/root/projects/tbs6909-drivers/media_build/v4l/firmware'
Kernel build directory is /lib/modules/5.18.5-200.fc36.x86_64/build
make -C ../linux apply_patches
make[2]: Entering directory '/root/projects/tbs6909-drivers/media_build/linux'
Syncing with dir ../../media
Patches for 5.18.5-200.fc36.x86_64 already applied.
make[2]: Leaving directory '/root/projects/tbs6909-drivers/media_build/linux'
make -C /lib/modules/5.18.5-200.fc36.x86_64/build M=/root/projects/tbs6909-drivers/media_build/v4l  modules
make[2]: Entering directory '/usr/src/kernels/5.18.5-200.fc36.x86_64'
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/msp3400-driver.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/msp3400-kthreads.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ccs-core.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ccs-reg-access.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ccs-quirk.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ccs-limits.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ccs-data.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/et8ek8_mode.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/et8ek8_driver.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cx25840-core.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cx25840-audio.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cx25840-firmware.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cx25840-vbi.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cx25840-ir.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/m5mols_core.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/m5mols_controls.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/m5mols_capture.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/aptina-pll.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tvaudio.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda7432.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa6588.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda9840.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda1997x.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tea6415c.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tea6420.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa7110.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa7115.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa717x.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa7127.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa7185.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/saa6752hs.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ad5820.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ak7375.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/dw9714.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/dw9768.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/dw9807-vcm.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7170.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7175.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7180.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7183.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7343.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7393.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7604.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7842.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ad9389b.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adv7511-v4l2.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/vpx3220.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/vs6624.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/bt819.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/bt856.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/bt866.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ks0127.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ths7303.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ths8200.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tvp5150.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tvp514x.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tvp7002.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tw2804.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tw9903.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tw9906.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tw9910.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cs3308.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cs5345.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/cs53l32a.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/m52790.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tlv320aic23b.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/uda1342.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/wm8775.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/wm8739.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/vp27smpx.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/sony-btf-mpx.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/upd64031a.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/upd64083.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov2640.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov2680.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov2685.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov5647.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov5648.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov5693.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov5695.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov6650.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov7251.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov7640.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov7670.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov7740.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov8865.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov9640.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov9734.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov13858.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov13b10.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9m001.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9m032.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9m111.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9p031.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9t001.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9t112.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9v011.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9v032.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt9v111.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/sr030pc30.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/noon010pc30.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/rj54n1cb0c.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5k6aa.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5k6a3.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5k4ecgx.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5k5baf.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5c73m3-core.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5c73m3-spi.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/s5c73m3-ctrls.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/adp1653.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/lm3560.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/lm3646.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ccs-pll.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ak881x.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ir-kbd-i2c.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/video-i2c.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ml86v7667.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/ov2659.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tc358743.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/hi846.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/imx214.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/imx219.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/imx290.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/imx355.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/max9271.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/rdacm20.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/rdacm21.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/st-mipid02.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/max2175.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tuner-xc2028.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tuner-simple.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tuner-types.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt20xx.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda8290.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tea5767.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tea5761.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda9887.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda827x.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda18271-maps.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda18271-common.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda18271-fe.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/tda18273.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/xc5000.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/xc4000.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/msi001.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt2060.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt2063.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt2266.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/qt1010.o
/root/projects/tbs6909-drivers/media_build/v4l/msi001.c:504:27: error: initialization of 'void (*)(struct spi_device *)' from incompatible pointer type 'int (*)(struct spi_device *)' [-Werror=incompatible-pointer-types]
  504 |         .remove         = msi001_remove,
      |                           ^~~~~~~~~~~~~
/root/projects/tbs6909-drivers/media_build/v4l/msi001.c:504:27: note: (near initialization for 'msi001_driver.remove')
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mt2131.o
  CC [M]  /root/projects/tbs6909-drivers/media_build/v4l/mxl5005s.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:288: /root/projects/tbs6909-drivers/media_build/v4l/msi001.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1838: /root/projects/tbs6909-drivers/media_build/v4l] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.18.5-200.fc36.x86_64'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/root/projects/tbs6909-drivers/media_build/v4l'
make: *** [Makefile:26: all] Error 2
+ exit 13

**Comment by tryptichon** [comment]
If you are familiar with patching, try this: https://github.com/tbsdtv/linux_media/issues/283#issuecomment-1162672107

**Comment by crazycat69** [comment]
Updated, now compatible with 4.14 - 6.2
