### ISSUE TITLE
Please add driver for TBS6209se. Thanks

### ISSUE THREAD

**Issue by snake2005** [tbsdtv/linux_media#297]

**Comment by snake2005** [comment]
I've downloaded the latest version from https://www.tbsdtv.com/download/index.html?path=14&id=148

TBS Download Center-Update the Latest Window & Linux Driver
https://www.tbsdtv.com
TBS Open Source Linux Driver Offline Package v20220424
they are installing fine on Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-132-generic x86_64)
but the problem is the poor or inexistent signal strength as I have other cards that works fine on dvb-c
Could you please help ?
Thanks

**Comment by crazycat69** [comment]
https://github.com/tbsdtv/linux_media/wiki

**Comment by snake2005** [comment]
@crazycat69 Thanks for your quick reply. Tried that and same issue. I've emailed TBS.
