### ISSUE TITLE
multiple cards not appearing

### ISSUE THREAD

**Issue by hamishegg** [tbsdtv/linux_media#30]
I have system with multiple cards
1 x tbs 6909 Octo
1 x tbs 6985 quad

I have installed latest version drivers but only octo card shows,
I install tbs v161031.zip drivers and both cards appear.

**Comment by crazycat69** [comment]
saa716x driver require 4.4+ kernel (because depend from cxd2820r frontend driver, which require regmap API support available in 4.4+).

**Comment by hamishegg** [comment]
Thanks will update only running 4.2.7
