### ISSUE TITLE
kernel 5.16 Compile error 

### ISSUE THREAD

**Issue by elkizana** [tbsdtv/linux_media#311]
`home/idoom/media_build/v4l/ov2740.c:1204:8: error: type defaults to 'int' in declaration of 'DEFINE_SIMPLE_DEV_PM_OPS' [-Werror=implicit-int]
 1204 | static DEFINE_SIMPLE_DEV_PM_OPS(ov2740_pm_ops, ov2740_suspend, ov2740_resume);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
/home/idoom/media_build/v4l/ov2740.c:1204:1: warning: parameter names (without types) in function declaration
 1204 | static DEFINE_SIMPLE_DEV_PM_OPS(ov2740_pm_ops, ov2740_suspend, ov2740_resume);
      | ^~~~~~
/home/idoom/media_build/v4l/ov2740.c:1216:23: error: implicit declaration of function 'pm_sleep_ptr' [-Werror=implicit-function-declaration]
 1216 |                 .pm = pm_sleep_ptr(&ov2740_pm_ops),
      |                       ^~~~~~~~~~~~
/home/idoom/media_build/v4l/ov2740.c:1216:37: error: 'ov2740_pm_ops' undeclared here (not in a function); did you mean 'ov2740_pad_ops'?
 1216 |                 .pm = pm_sleep_ptr(&ov2740_pm_ops),
      |                                     ^~~~~~~~~~~~~
      |                                     ov2740_pad_ops
/home/idoom/media_build/v4l/ov2740.c:1204:8: warning: 'DEFINE_SIMPLE_DEV_PM_OPS' declared 'static' but never defined [-Wunused-function]
 1204 | static DEFINE_SIMPLE_DEV_PM_OPS(ov2740_pm_ops, ov2740_suspend, ov2740_resume);
      |        ^~~~~~~~~~~~~~~~~~~~~~~~
/home/idoom/media_build/v4l/ov2740.c:839:12: warning: 'ov2740_resume' defined but not used [-Wunused-function]
  839 | static int ov2740_resume(struct device *dev)
      |            ^~~~~~~~~~~~~
/home/idoom/media_build/v4l/ov2740.c:825:12: warning: 'ov2740_suspend' defined but not used [-Wunused-function]
  825 | static int ov2740_suspend(struct device *dev)
      |            ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:287: /home/idoom/media_build/v4l/ov2740.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:1852: /home/idoom/media_build/v4l] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.16.20-051620-generic'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/home/idoom/media_build/v4l'
make: *** [Makefile:26: all] Error 2
`

**Comment by elkizana** [comment]
compiled fine with "master"
to close

**Comment by crazycat69** [comment]
487a1584559fee4fe1478ddf7e35b304fed54f3b

**Comment by elkizana** [comment]
thanks 
how can update the the media_folder ?

**Comment by crazycat69** [comment]
another [update](https://github.com/tbsdtv/media_build/commit/281a3f023034f96ebb571838119de60249d1d30d), tested with 5.16.20-051620-generic

**Comment by elkizana** [comment]
compiled but unfortunately the graphics are broken, nouveau doesn't seem to work 

![Screenshot from 2023-04-28 19-52-12](https://user-images.githubusercontent.com/53874333/235230217-ae8536b6-9624-4dac-b132-569c541934e8.png)

**Comment by crazycat69** [comment]
Use install.sh script

**Comment by elkizana** [comment]
did it the problem still

**Comment by crazycat69** [comment]
Maybe you delete kernel media modules before install ?

**Comment by elkizana** [comment]
> Maybe you delete kernel media modules before install ?

suggest me something to do ?

**Comment by crazycat69** [comment]
what dvb device used ?

**Comment by elkizana** [comment]
TechniSat SkyStar 2 eXpress HD 
I have tested several kernels; kernels 5.10 and below work fine. The ones above 5.10 install but broke the graphics.

**Comment by elkizana** [comment]
[dmesg.txt](https://github.com/tbsdtv/linux_media/files/11377410/dmesg.txt)

**Comment by elkizana** [comment]
it's working now. I installed it with the the and executed the commands. Strange.

**Comment by crazycat69** [comment]
ok
you use old unsupported kernels 5.16, 5.18 instead current ubuntu kernels ?

**Comment by elkizana** [comment]
Now i'm using 5.18.0
Thank you for the work you are doing for the community @crazycat69
