### ISSUE TITLE
generated/autoconf.h: No such file or directory

### ISSUE THREAD

**Issue by LukeLR** [tbsdtv/linux_media#320]
When trying to follow the build instructions on the wiki, the `make -j4` step fails with:

```
  CC [M]  /home/user/git/media_build/v4l/max2175.o
In file included from <command-line>:
././include/linux/kconfig.h:5:10: fatal error: generated/autoconf.h: No such file or directory
    5 | #include <generated/autoconf.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

`find /home/user/git` -iname autoconf.h` also yields no results. System is an up-to-date Arch Linux with kernel version 6.4.12-arch1-1. Any ideas?

**Comment by tmn505** [comment]
Did You install linux headers for that kernel version?
