### ISSUE TITLE
DVB: Unable to find symbol av201x_attach()

### ISSUE THREAD

**Issue by alfrup** [tbsdtv/linux_media#334]
compilation for TBS6590 device with kernel 6.6.2. (opensuse tumbleweed) is ok. 
card doesn't work -

dmesg:
[    3.035796] si2157 4-0060: Silicon Labs Si2157 successfully attached
[    3.037384] DVB: Unable to find symbol av201x_attach()
[    3.037390] TBSECP3 driver 0000:08:00.0: frontend 0 tuner attach failed
[    3.037396] TBSECP3 driver 0000:08:00.0: TBSECP3 frontend 0 attach failed
[    3.037400] TBSECP3 driver 0000:08:00.0: frontend attach failed
[    3.037527] TBSECP3 driver 0000:08:00.0: adapter0 attach failed
[    3.037532] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[    3.060669] usb 2-5: new full-speed USB device number 3 using xhci_hcd
[    3.098521] sr 5:0:0:0: [sr0] scsi3-mmc drive: 48x/48x writer dvd-ram cd/rw xa/form2 cdda tray
[    3.098524] cdrom: Uniform CD-ROM driver Revision: 3.20
[    3.143063] TBSECP3 driver 0000:08:00.0: MAC address 00:22:ab:d1:6b:07
[    3.144615] si2183 0-0067: Silicon Labs Si2183 successfully attached
[    3.147948] si2157 4-0061: Silicon Labs Si2157 successfully attached
[    3.148157] sr 5:0:0:0: Attached scsi CD-ROM sr0
[    3.149766] DVB: Unable to find symbol av201x_attach()
[    3.149771] TBSECP3 driver 0000:08:00.0: frontend 1 tuner attach failed
[    3.149776] TBSECP3 driver 0000:08:00.0: TBSECP3 frontend 1 attach failed
[    3.149780] TBSECP3 driver 0000:08:00.0: frontend attach failed
[    3.149904] TBSECP3 driver 0000:08:00.0: adapter1 attach failed

dmesg | grep dvb
 d0a7e44358f28064697e0eed309db03166dcd83b media: dvb-frontends/stid135: Unlock demod before search in stid135_set_parameters().
 0a7e44358f28064697e0eed309db03166dcd83b media: dvb-frontends/stid135: Unlock demod before search in stid135_set_parameters().
[    1.023139] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[    3.037532] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)

**Comment by crazycat69** [comment]
```
modinfo av210x
modprobe av210x

```

**Comment by alfrup** [comment]
modinfo av210x 
modinfo: ERROR: Module av210x not found.

modprobe av210x 
modprobe: FATAL: Module av210x not found in directory
/usr/lib/modules/6.6.2-1-default

**Comment by crazycat69** [comment]
sorry, wrong module name :) **av201x**

**Comment by alfrup** [comment]
with snapshot tumbleweed 20231130 (new kernel 6.6.3) its all OK.
Compilation OK, TV-Card is recognized

modinfo av201x
filename:       /usr/lib/modules/6.6.3-1-
default/updates/extra/media/tuners/av201x.ko
license:        GPL
author:         Luis Alves ***@***.***>
description:    Airoha Technology AV201x silicon tuner driver
suserelease:    openSUSE Tumbleweed
srcversion:     8548B886C8B02EC86B4227F
depends:         
retpoline:      Y
name:           av201x
vermagic:       6.6.3-1-default SMP preempt mod_unload modversions 

Thank you


-------- Ursprüngliche Nachricht --------
Von: CrazyCat ***@***.***>
Antwort an: tbsdtv/linux_media
***@***.***>
An: tbsdtv/linux_media ***@***.***>
Kopie: alfrup ***@***.***>, Author ***@***.***>
Betreff: Re: [tbsdtv/linux_media] DVB: Unable to find symbol
av201x_attach() (Issue #334)
Datum: 02.12.2023 17:04

sorry, wrong module name :) av201x
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:
***@***.***>
