### ISSUE TITLE
TBS 6981: remote?

### ISSUE THREAD

**Issue by NielsCharlier** [tbsdtv/linux_media#341]
I successfully managed to get the driver to work with my **TBS 6981** card, except for the remote control. There is no remote control device being registered.

I find conflicting information on whether the remote control is supposed to work. It would really be a shame if I can't use it any more.

**Comment by crazycat69** [comment]
Not need install TBS media_build for 6980/6981,
Support for this cards available in kernel with RC support
Only need install firmwares from [dvb-firmwares.tar.bz2](https://github.com/tbsdtv/media_build/releases/download/latest/dvb-firmwares.tar.bz2). Need at least **v4l-cx23885-avcore-01.fw**, **dvb-fe-cx24117.fw** on /lib/firmware

**Comment by NielsCharlier** [comment]
Hello, are you sure though, because my ubuntu is ancient. 18.04.6 kernel 4.15.0-213-generic
I upgraded from an even more ancient mythbuntu, the TV card and remote control worked on there with the official closed source driver. After upgrade the TV card didn't seem to work out of the box but it did after installing TBS media_build.

I have exactly those files in /lib/firmware. There is no trace of a remote control at all.
