### ISSUE TITLE
Compilation error on latest Debian 12 kernel: 6.1.0-25-amd64 / 6.1.106-3

### ISSUE THREAD

**Issue by ritzmann** [tbsdtv/linux_media#358]
I am attaching the complete build log.
[build.log](https://github.com/user-attachments/files/16828813/build.log)

**Comment by crazycat69** [comment]
some internal compiler error

**Comment by ritzmann** [comment]
Managed to work around it by adding a swap file for the duration of the compilation. The host has 4 GB RAM and a 4 GB swap partition but that apparently was not sufficient.
