### ISSUE TITLE
Build Error Ubuntu 16.04.04 Kernel  4.8.0-34-generic

### ISSUE THREAD

**Issue by pk1057** [tbsdtv/linux_media#38]
make[2]: Entering directory '/usr/src/linux-headers-4.8.0-34-generic'
  CC [M]  /usr/local/src/tbs-oss/media_build/v4l/em28xx-dvb.o
/usr/local/src/tbs-oss/media_build/v4l/em28xx-dvb.c:47:31: fatal error: drx39xyj/drx39xxj.h: No such file or directory
compilation terminated.
scripts/Makefile.build:295: die Regel für Ziel „/usr/local/src/tbs-oss/media_build/v4l/em28xx-dvb.o“ scheiterte

**Comment by steven1758** [comment]
Hi 

check the FAQ here :
https://github.com/tbsdtv/linux_media/wiki

3.fatal error: drx39xyj/drx39xxj.h: No such file or directory
mkdir -p v4l/drx39xyj
cp v4l/drx39xxj.h v4l/drx39xyj/

Thanks
