### ISSUE TITLE
TBS 6909 - modprobe what?

### ISSUE THREAD

**Issue by barhom** [tbsdtv/linux_media#5]
Hello,

In the TBS (not open source) you do "modprobe tbs_pcie-dvb" to load 6909.
But what do you run in in there open source one?

modprobe tbs_pcie-dvb
modprobe: FATAL: Module tbs_pcie-dvb not found.

**Comment by crazycat69** [comment]
tbsecp3

**Comment by barhom** [comment]
Thanks!

This should be added to the wiki!
