### ISSUE TITLE
linux-4.12.x and up: saa716x failes to build (has to change msi-x to the new pci_alloc_irq_vectors api)

### ISSUE THREAD

**Issue by bas-t** [tbsdtv/linux_media#51]
linux-4.12-rc1: saa716x failes to build due to

https://patchwork.kernel.org/patch/9667025/

Failing with:

drivers/media/pci/saa716x/saa716x_pci.c: In function ‘saa716x_enable_msix’:
drivers/media/pci/saa716x/saa716x_pci.c:46:8: error: implicit declaration of function ‘pci_enable_msix’ [-Werror=implicit-function-declaration]
  ret = pci_enable_msix(pdev, saa716x->msix_entries, SAA716x_MSI_MAX_VECTORS);
        ^~~~~~~~~~~~~~~

Obviously, there are quite a few more places where the build should fail, if it continued after the first failure.

I really hope that you guys can patch saa716x so it can live past linux-4.12.x.
Kind regards,
Tycho.

**Comment by bas-t** [comment]
The above mentioned patch is part 4 of 4. Maybe the other ones are interesting too:

https://patchwork.kernel.org/patch/9667013/

https://patchwork.kernel.org/patch/9667023/

https://patchwork.kernel.org/patch/9667027/

Regards, Tycho.

**Comment by crazycat69** [comment]
saa716x: replace pci_enable_msix() with pci_enable_msix_exact() 
fb349ffe41d5e198088bd046bd1c82dacf4eb8c4

**Comment by bas-t** [comment]
@crazycat69 Thanks, applied in https://github.com/bas-t/saa716x/commit/75eb1e63111a74b2135dd01ab524cee7f37e063b and compiling right now.
Will report back.
Cheers!

**Comment by bas-t** [comment]
@crazycat69 
Works OK for me.
Going to test backwards compatibility with a regular Debian Stretch stock kernel (4.9.whatever)
If that test succeeds too, I'll close the issue.
Thanks again and regards,
Tycho.

**Comment by bas-t** [comment]
Backwards compatibility with a regular Debian Stretch stock kernel confirmed.
