### ISSUE TITLE
cx231xx bulk mode as default

### ISSUE THREAD

**Issue by cz172638** [tbsdtv/linux_media#52]
when i tried play hd or encrypted channel, i had horrible performance, even signal was great.
after googling i realized that i need following in /etc/modprobe.d/cx231xx.conf

`
options cx231xx transfer_mode=0
`

shouldn't be bulk mode default for streaming media?

**Comment by crazycat69** [comment]
305933f20af65cc97c12e000dd38709024a95ca9

**Comment by cz172638** [comment]
just tested
