### ISSUE TITLE
i can't install tbs6522 on ubuntu 16.04 lts

### ISSUE THREAD

**Issue by mounir3539** [tbsdtv/linux_media#66]
Hello;

I am a new linux user
after i follow the steps to install driver of tbs 6522 i got problem when i reach make install

 Installing kernel modules under /lib/modules/4.4.0-83-generic/kernel/drivers/media/:
	pci/cx25821/: install: cannot create directory '/lib/modules/4.4.0-83-generic/kernel/drivers/media/pci': Permission denied
cx25821-alsa.ko install: cannot create regular file '/lib/modules/4.4.0-83-generic/kernel/drivers/media/pci/cx25821': No such file or directory
cx25821.ko install: cannot create regular file '/lib/modules/4.4.0-83-generic/kernel/drivers/media/pci/cx25821': No such file or directory

strip: '/lib/modules/4.4.0-83-generic/kernel/drivers/media/pci/cx25821/*.ko': No such file
Makefile.media:1750: recipe for target 'media-install' failed
make[1]: *** [media-install] Error 1
make[1]: Leaving directory '/home/ahmed/tbsdriver/media_build/v4l'
Makefile:15: recipe for target 'install' failed
make: *** [install] Error 2

can ytou help me to solve this problem ?

**Comment by crazycat69** [comment]
Need root permission for install kernel modules. You can use: sudo make install
