### ISSUE TITLE
How fix Error install driver on fedora 26 with kernel 4.12.9 ?!

### ISSUE THREAD

**Issue by sajjads24** [tbsdtv/linux_media#73]
hi
how fix install error driver on fedora 26 with kernel 4.12.9 :
https://pastebin.com/KuGQ3hVK
how fix ?

plz helpe me.

**Comment by crazycat69** [comment]
This only warning about missed some perl library ProcessTable, read FAQ @ wiki ( Cent OS related ). But anyway drivers compiled and installed, reboot need.

**Comment by sajjads24** [comment]
thanks
