### ISSUE TITLE
TBS6902 and clone TBS6922 do not work correctly with no lnb settings

### ISSUE THREAD

**Issue by bastard79** [tbsdtv/linux_media#84]
Hi, i'm using tt budget s2-4100 (clone TBS6922) with your latest drivers on ubuntu 17.04 64bit with tvheadend and kodi and everything works ok, few days ago i bought TBS 6902 to connect 2 more tvs and it doesnt work properly - there is no lnb option for both adapters. 
when i plugin booth card, i have only lnb option for TBS6922, TBS6902 no lnb option :(, when i plugin only TBS6902 i have still one lnb option i think it might be drivers problem.

more information in tvheadend page https://tvheadend.org/boards/4/topics/27660?r=28839#message-28839

please help to solve this issue.
`xbmc@ubuntu:~$ dmesg
[    0.000000] Linux version 4.10.0-20-generic (buildd@lcy01-05) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #22-Ubuntu SMP Thu Apr 20 09:22:42 UTC 2017 (Ubuntu 4.10.0-20.22-generic 4.10.8)
[    6.593294] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[    6.758093] dvbdev: DVB: registering new adapter (SAA716x dvb adapter)
[    6.961320] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[    6.961287] TBSECP3 driver 0000:03:00.0: DVB: registering adapter 0 frontend                                                           0 (TurboSight TBS 6902 DVB-S/S2 )...
[    7.067449] SAA716x Budget 0000:02:00.0: DVB: registering adapter 1 frontend                                                           0 (TurboSight TBS 6922 DVB-S/S2)...
[    7.186787] TBSECP3 driver 0000:03:00.0: DVB: registering adapter 2 frontend                                                           0 (TurboSight TBS 6902 DVB-S/S2 )...
[   19.027161] TBSECP3 driver 0000:03:00.0: DVB: adapter 2 frontend 0 frequency 0 out of range (950000..2150000)
[   19.451220] SAA716x Budget 0000:02:00.0: DVB: adapter 1 frontend 0 frequency 0 out of range (950000..2150000)
[   20.019273] TBSECP3 driver 0000:03:00.0: DVB: adapter 0 frontend 0 frequency 0 out of range (950000..2150000)

`

**Comment by crazycat69** [comment]
Hi,
Please provide kernel log (dmesg). Some wrong on frontend attach.

P.S. saa716x and tbsecp3 drivers have some issues with current not-LTS kernels >4.9. I plan install and verify *buntu 17.04, but no time since spring 2017 :-) So i recomend LTS Ubuntu 16.04 or 14.04.5 with 4.4 kernel. Or Debian 9 with 4.9 kernel.

**Comment by bastard79** [comment]
here is full dmesg https://pastebin.com/wAztuwcy

may i install only lts kernel from latest lts ubuntu 16.04?  i can install from scratch 16.04 or debian 9 but there is no sure to resolve my problem. i bought tbs6902 becasue i thought it working with exist TBS6922 clone with any issue on the same compiled drivers

**Comment by bastard79** [comment]
installed 4.4 and 4.9, compiled drivers for 4.4 result is the same as in 4.10
full dmesg https://pastebin.com/AF6B6pFR
now compiling for 4.9

**Comment by crazycat69** [comment]
I not see any errors in logs, all three dvb adapter registered. You not see LNB option for adapter 2 because you configure it as slave to adapter 1.

**Comment by crazycat69** [comment]
You need fix adapter enumeration with module options. Put this lines to /etc/modprobe.d/dvb.conf:
```
options saa716x_core adapter_nr=0
options tbsecp3 adapter_nr=1,2
```

**Comment by bastard79** [comment]
I SOLVE THE ISSUE !!!
https://tvheadend.org/boards/4/topics/27660?r=28896#message-28896

**Comment by crazycat69** [comment]
Ok :-)

**Comment by dtwxds** [comment]
老师们，我是新手，刚买tbs6902，有教程安装吗？

**Comment by steven1758** [comment]
> 老师们，我是新手，刚买tbs6902，有教程安装吗？

https://www.tbsiptv.com/help_center/  windows 和 linux dou you 安装指导

**Comment by dtwxds** [comment]
Thank&nbsp;you&nbsp;very&nbsp;much&nbsp;for&nbsp;letting&nbsp;them&nbsp;contradict&nbsp;each&nbsp;other.&nbsp;Is&nbsp;Linux&nbsp;easy&nbsp;to&nbsp;operate&nbsp;and&nbsp;install?&nbsp;I'm&nbsp;just&nbsp;not&nbsp;very&nbsp;good&nbsp;at&nbsp;installing&nbsp;drivers&nbsp;and&nbsp;tvheadend


---Original---
From: ***@***.***&gt;
Date: Fri, Feb 6, 2026 15:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tbsdtv/linux_media] TBS6902 and clone TBS6922 do not workcorrectly with no lnb settings (#84)


steven1758 left a comment (tbsdtv/linux_media#84)
  
老师们，我是新手，刚买tbs6902，有教程安装吗？
  
https://www.tbsiptv.com/help_center/  windows 和 linux dou you 安装指导
