### ISSUE TITLE
Can't select ISDB-T network under TVHeadend because driver uses old Linux DVBAPI

### ISSUE THREAD

**Issue by mpaolino** [tbsdtv/linux_media#88]
I have a TBS6814 and I have installed and tested the last driver available with MythTV and it works fine.
I'm using kernel 4.8.0-30-generic on a 64bit Ubuntu.

The problem is that it doesn't work with TVHeadend because the drivers report the card as a DVB-T card, and the software does not allow to select a ISDB-T network to use. Apparetky this is because the drivers are using an old Linux DVBAPI. BTW, MythTV also reports the card as DVB-T.

![screenshot from 2017-11-13 18-12-47](https://user-images.githubusercontent.com/757973/32749608-9615a3ce-c89e-11e7-91e2-198b8d255b47.png)

[The related issue in TVHeadend bug tracker and response from developers](https://tvheadend.org/issues/4146).

**Comment by crazycat69** [comment]
You use old semi-closed source linux-tbs-drivers.
Install open-source tbsdtv drivers and your 6814 must  be ISDB-T tuner + modern DVB-API 5.10

**Comment by mpaolino** [comment]
[I don't see it in the list of supported cards](https://github.com/tbsdtv/linux_media/wiki), but I'll give it a try and let you know.

**Comment by crazycat69** [comment]
added to wiki list :)

**Comment by mpaolino** [comment]
I can confirm it works, thanks.
